### ISSUE TITLE
Birds eat spiders

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#367] opened 2019-02-07 15:26 UTC
**Is your feature request related to a problem? Please describe.**

Birds eat spiders. This damages the spider, but increases the health of the bird.

**Describe the solution you'd like**

Write a test to do so.
Then make that test come true.

**Describe alternatives you've considered**

None.

**Additional context**

You can use the test to see that grass is eaten by a cow.

**Comment by Joshua260403** [comment] 2019-02-08 11:43
Pretty sure this is done already, will check it out tonight

**Comment by Joshua260403** [comment] 2019-02-08 13:15
Duplicate of #289, it was already added there, just like #366

**Closed by Joshua260403** 2019-02-08 13:15 UTC
Labels: medium priority
