### ISSUE TITLE
Rotating a tile should not be possible when it results in an overlap

### ISSUE THREAD

**Issue by antonhensen81** [richelbilderbeek/djog_unos_2018#481] opened 2019-03-15 18:57 UTC
WARNING: THIS IS PROBABLY PREMATURE - DO NOT FIX. Martje is still working out the rotating feature, so let's wait for that first ;-)

~~
**Describe the bug**
When I have a tile in a position where it would cause an overlap with another tile after rotating, it should not be possible to rotate it. 

**To Reproduce**
- Move a tile to a position adjacent to another tile
- Press R
- In some cases you will notice the overlap. See screenshot for an example
 
**Expected behavior**
This should not be possible. Simply don't rotate the tile in such a case

**Screenshots**
Before rotating:
![image](https://user-images.githubusercontent.com/4269117/54455566-74950f80-475c-11e9-983e-512e14cfb70d.png)

After rotating:
![image](https://user-images.githubusercontent.com/4269117/54455584-7eb70e00-475c-11e9-9734-41c262024b82.png)

~~

**Comment by Joshua260403** [comment] 2019-03-17 13:45
yeah @martje127 is working on this in his issue making it a Duplicate of #463

**Comment by Joshua260403** [comment] 2019-03-17 13:45
Duplicate of #463

**Closed by Joshua260403** 2019-03-17 13:45 UTC
Labels: medium priority
