### ISSUE TITLE
Research Steam Stuff

### ISSUE THREAD

**Issue by RafayelGardishyan** [richelbilderbeek/djog_unos_2018#576] opened 2019-04-25 19:40 UTC
Research what we need to do and make a checklist for uploading our game to steam

**Comment by richelbilderbeek** [comment] 2019-05-03 16:02
For @RafayelGardishyan, this is a duplicate of #484: he will take care of the Steam Pipe.

The other Issues will be created when @antonhensen81 can access the Steam account.

Due to this, closing this Issue.

**Closed by richelbilderbeek** 2019-05-03 16:02 UTC
Labels: medior, medium priority
